version: '3.4'

services:

  pr-agent:
    image: pr-agent:github-app
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: github_app
    ports:
      - "5432:5432"
    volumes:
      - ./pr_agent/settings/.secrets.toml:/app/pr_agent/settings/.secrets.toml
  
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod-stage
    container_name: PR-Agent-NGINX
    ports:
      - "80:80"
    depends_on:
      - pr-agent
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf